# remove-empty = true
append-when-occupied = true
# min = 1
# max = 30
remove-empty = false
# append-when-occupied = false
renamers = ["classified", "constant"]
[names]
constant = ""
# 
[[names.classified]]
"" = [] # Browser
"" = ["kitty"] # Terminal
"" = ["itch"] # Game
"" = ["Element"] # Chat
"" = [] # Music
"" = ["Thunar"] # Files
"" = ["feh"] # Image
#Specific programs
"" = ["firefox"]
"戮" = ["Steam"]
"ﭮ" = ["discord"]
"切" = ["TelegramDesktop"]
"阮" = ["Spotify"]
