#!/bin/sh
_OPTS="--archive --verbose --info=progress2 --no-inc-recursive --human-readable"
_SSH_CMD="ssh -p 8022"
_HOST="192.168.1.103"
_SOURCE="/storage/689A-AAEB/TEST3/"
_DEST="$HOME/.hidden/"
exec rsync $_OPTS --rsh="ssh -p 8022" "$_HOST:$_SOURCE" "$_DEST"
