#!/bin/sh
_OPTS="--archive --verbose --info=progress2 --delete --no-inc-recursive"
_SSH_CMD="ssh -p 8022"
_HOST="10.0.0.11"
_SOURCE="/storage/689A-AAEB/TEST3/"
_DEST="$HOME/.hidden/"
exec rsync $_OPTS --rsh="ssh -p 8022" "$_HOST:$_SOURCE" "$_DEST"
