#! /bin/sh
export SXHKD_SHELL='/bin/sh'
export _JAVA_AWT_WM_NONREPARENTING=1
sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

xrdb ~/.Xresources
xsetroot -cursor_name left_ptr
bspc config normal_border_color "$(xrdb-query 0)"
bspc config active_border_color "$(xrdb-query 8)"
bspc config focused_border_color "$(xrdb-query 6)"
bspc config presel_feedback_color "$(xrdb-query 6)"

#rules
bspc config external_rules_command "/home/socks/.config/bspwm/external_rules"
bspc rule -a scratch sticky=on state=floating hidden=on

#polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

#graphical setup
setxkbmap -option compose:ralt
feh --bg-fill --no-fehbg /usr/share/backgrounds/custom/socc.png
~/.config/polybar/launch.sh
~/.scripts/restart.sh picom

#xdg autostart
dex -ae bspwm
