#! /bin/sh
export SXHKD_SHELL='/bin/sh'
export _JAVA_AWT_WM_NONREPARENTING=1
sxhkd &

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

xrdb ~/.Xresources
xsetroot -cursor_name left_ptr
bspc config normal_border_color "$(~/.scripts/utils/xrdb-query color0)"
bspc config active_border_color "$(~/.scripts/utils/xrdb-query color8)"
bspc config focused_border_color "$(~/.scripts/utils/xrdb-query color6)"
bspc config presel_feedback_color "$(~/.scripts/utils/xrdb-query color6)"

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
setxkbmap -option compose:ralt
feh --bg-fill --no-fehbg ~/.config/background
~/.config/polybar/launch.sh
picom --experimental-backends &
~/.scripts/utils/dumb-restart playerctld
~/.scripts/utils/dumb-restart btops

dex -ae bspwm
